language: python
python:
  - 2.6
  - 2.7
  - 3.3
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - flake8 translate
  - py.test test/
install:
  - pip install -r requirements.txt --use-mirrors
notifications:
  email: false
