language: python
python:
  - 2.6
  - 2.7
#  - 3.3
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
# Please don't abuse this key. It's just for testing here.
  - export YANDEX_KEY='trnsl.1.1.20130706T202805Z.b7d63d1fa6f4f01e.53032bf4bed3ebc43b7589eb27acc4cb090595bf'
script:
  - flake8 translate
  - py.test tests
install:
  - sudo apt-get install python-all-dev
  - sudo apt-get install apertium apertium-en-es
  - pip install -r requirements.txt --use-mirrors
notifications:
  email: false
