language: python
python:
  - 2.6
  - 2.7
#  - 3.3
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - flake8 translate
  - py.test tests
install:
  - sudo apt-get install python-all-dev
  - sudo apt-get install apertium apertium-en-es
  - pip install -r requirements.txt --use-mirrors
notifications:
  email: false
